spring:
  datasource:
    url: jdbc:h2:~/springboot-jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true
      path: /console

logging:
  level:
    org.hibernate.type: debug
